name: Upload screenshot

on:
  push:
    branches:
      - main

jobs:
  s3-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: website-archive
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_s3_bucket: ${{ secrets.AWS_BUCKET }}
          DESTINATION_DIR: spencerchang.me-${{ steps.date.outputs.date }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_DEFAULT_OUTPUT: json
        run: |
          aws --version
          aws s3 ./website.png s3://$aws_s3_bucket/$DESTINATION_DIR
